const custmorData = [
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date: "4 Apr 2021",
        time: "03:21:38 pm",
        smsProvider: "Sulekha",
        number: 8272627282,
        actionTaken: "No Action Taken",
        actionDate: "6 Apr 2021",
        actionTime: "02:11:22 pm",
        cradit: "0.02",
        sms: "it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
    },
    {
        date:"4 Apr 2021",
        time:"03:21:38 pm",
        smsProvider:"Sulekha",
        number:8272627282,
        actionTaken:"No Action Taken",
        actionDate:"6 Apr 2021",
        actionTime:"02:11:22 pm",
        cradit:"0.02",
        sms:"it is long established fact that render will be distracted by the readable contrnt of the page when looking at the layout ",
        },
]
module.exports.custData=custmorData